<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Uploads\**" />
    <Content Remove="Uploads\**" />
    <PackageReference Include="Microsoft.Extensions.Resilience" Version="10.6.0" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.73.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Google" Version="1.73.0-alpha" />
    <EmbeddedResource Remove="Uploads\**" />
    <None Remove="Uploads\**" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Core.8.Utility.Web" Version="2.26.313" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
    <PackageReference Include="Hangfire.InMemory" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.23" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.73.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Google" Version="1.73.0-alpha" />
    <PackageReference Include="NPOI" Version="2.6.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.DirectoryServices.Protocols" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Business\Business.csproj" />
    <ProjectReference Include="..\Const\Const.csproj" />
    <PackageReference Include="Sander.Platform.DbTransfer" Version="1.0.0" />
    <PackageReference Include="Sander.Platform.Web" Version="1.0.0" />
    <ProjectReference Include="..\ViewModel\ViewModel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Hubs\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
