<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\assets\libs\choices.js\**" />
    <Content Remove="wwwroot\assets\libs\choices.js\**" />
    <EmbeddedResource Remove="wwwroot\assets\libs\choices.js\**" />
    <None Remove="wwwroot\assets\libs\choices.js\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Views\Icons\Boxicons.cshtml" />
    <None Include="Views\Icons\CryptoSVG.cshtml" />
    <None Include="Views\Icons\Feather.cshtml" />
    <None Include="Views\Icons\LineAwesome.cshtml" />
    <None Include="Views\Icons\MaterialDesign.cshtml" />
    <None Include="Views\Icons\Remix.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Core.8.Utility" Version="3.26.518.1" />
    <PackageReference Include="Core.8.Utility.Web" Version="2.26.313" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.23" />
    <PackageReference Include="System.DirectoryServices.Protocols" Version="8.0.0" />
    <PackageReference Include="System.Diagnostics.Debug" Version="4.3.0" />
    <PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Runtime.InteropServices" Version="4.3.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Const\Const.csproj" />
    <ProjectReference Include="..\ViewModel\ViewModel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Hubs\" />
  </ItemGroup>

</Project>
